#+title: Libre Source License
#+subtitle: Version 1 (Draft), {{{time(%Y-%m-%d)}}}
#+author:
#+options: toc:nil

*Contributor:* =Licensor Name=

*Source Code:* =https://example.com/project=

If you follow the rules below, you may do everything with this software that would otherwise infringe either any contributor's copyright in it, any patent claim any contributor can license that covers this software as of that contributor's latest contribution, or both.

1. Ensure everyone who gets a copy of this software from you, in any form, gets the text of this license and the contributor and source code lines above.

2. Ensure everyone who gets a copy of this software from you, in any form other than source code, gets the corresponding source code.

3. License all changes you make to this software under this license, publish the corresponding source code, in the preferred form for making changes, through a freely accessible distribution system commonly used for similar source code, and ensure reasonable availability of each such publication for at least 180 days.

4. Do not make any legal claim against anyone for infringing any patent claim they would infringe by using this software alone, accusing this software, with or without changes, alone or as part of a larger application.

#+begin_quote
There is no warranty for this software, to the extent permitted by applicable law. Except when otherwise stated in writing the copyright holders and/or other parties provide this software "as is" without warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose. The entire risk as to the quality and performance of this sofware is with you. Should this software prove defective, you assume the cost of all necessary servicing, repair or correction.
#+end_quote

#+begin_quote
In no event, unless required by applicable law or agreed to in writing, will any copyright holder, or any other party who makes changes to and/or distributes this software as permitted above, be liable to you for damages, including any general, special, incidental, or consequential damages arising out of the use or inability to use this software (including but not limited to loss of data or data being rendered inaccurate or losses sustained by you or third parties or a failure of this software to operate with any other software, hardware, or wetware), even if such holder or other party has been advised of the possibility of such damages.
#+end_quote

#+begin_quote
Everyone is permitted to copy and distribute verbatim copies of this license.
#+end_quote
