* Contribution Public License 1.0 (Draft)

*Copyright Notice:* © =Year and Copyright Holder=

*Source Notice:* =Primary location of source code=

You may use and distribute this software in any form, with or
without changes, as long as you meet all of the following conditions:

1. Ensure everyone who receives a copy of this software from you,
   in any form, also receives the text of this license and the
   copyright and source notices above.

2. Contribute each change you make to this software as follows:
   License it under this license to the public, publish it through
   a freely accessible distribution system commonly used for
   similar changes, and ensure reasonable availability of it via
   one such publication for as long as you use or distribute
   this software with it.

You are excused for unknowingly violating the above conditions
if you comply with them within 30 days of learning you violated them.

#+begin_quote
There is no warranty for this software, to the extent permitted by applicable law. Except when otherwise stated in writing the copyright holders and/or other parties provide this software "as is" without warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose. The entire risk as to the quality and performance of this sofware is with you. Should this software prove defective, you assume the cost of all necessary servicing, repair or correction.
#+end_quote

#+begin_quote
In no event, unless required by applicable law or agreed to in writing, will any copyright holder, or any other party who makes changes to and/or distributes this software as permitted above, be liable to you for damages, including any general, special, incidental, or consequential damages arising out of the use or inability to use this software (including but not limited to loss of data or data being rendered inaccurate or losses sustained by you or third parties or a failure of this software to operate with any other software, hardware, or wetware), even if such holder or other party has been advised of the possibility of such damages.
#+end_quote

#+begin_quote
Everyone is permitted to copy and distribute verbatim copies of this license.
#+end_quote
