#+title: Libre Source License
#+subtitle: Version 1 (Draft), {{{time(%Y-%m-%d)}}}
#+author:
#+options: toc:nil

*Contributor Notice:* =Licensor Name=

*Source Notice:* =Primary location of source code=

Everyone is permitted to copy and distribute verbatim copies of this license.

* Grants
:PROPERTIES:
:CUSTOM_ID: grants
:END:

In exchange for your promise to fulfill all of the obligations listed in section [[#obligations]] you may do everything with this software that would otherwise infringe either any contributors' copyright in it, any patent claim any contributor can license that covers this software as of that contributor's latest contribution, or both. Specifically:

- You are granted a perpetual, universal, non-exclusive, no-charge, royalty-free, irrevocable (except in the case of breaching the obligations listed in section [[#obligations]]) copyright license without scope limitations.

- You are granted a perpetual, universal, non-exclusive, no-charge, royalty-free, irrevocable (except in the case of breaching the obligations listed in section [[#obligations]]) patent license for all patent claims covering contributions as embodied in this software and licensable by respective contributors without other scope limitations.

* Obligations
:PROPERTIES:
:CUSTOM_ID: obligations
:END:

1. Ensure everyone who receives a copy of this software from you, in any form, also receives the text of this license and the contributor and source notices above.

2. License each change you make to this software under this license, publish it in its original form through a freely accessible distribution system commonly used for similar changes, and ensure reasonable availability of it via one such publication for as long as you use the rights granted in section [[#grants]], but no less than 180 days.

3. Do not make any legal claim against anyone for infringing any patent claim they would infringe by using this software alone, accusing this software, with or without changes, alone or as part of a larger application.

* Disclaimer of Warranty

There is no warranty for this software, to the extent permitted by applicable law. Except when otherwise stated in writing the copyright holders and/or other parties provide this software "as is" without warranty of any kind, either expressed or implied, including, but not limited to, the implied warranties of merchantability and fitness for a particular purpose. The entire risk as to the quality and performance of this sofware is with you. Should this software prove defective, you assume the cost of all necessary servicing, repair or correction.

* Limitation of Liability

In no event, unless required by applicable law or agreed to in writing, will any copyright holder, or any other party who makes changes to and/or distributes this software as permitted above, be liable to you for damages, including any general, special, incidental, or consequential damages arising out of the use or inability to use this software (including but not limited to loss of data or data being rendered inaccurate or losses sustained by you or third parties or a failure of this software to operate with any other software, hardware, or wetware), even if such holder or other party has been advised of the possibility of such damages.
